main/urls.py
from django.urls import include, path

from . import views

from story1 import views as story1_views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('hobby/', views.hobby, name='hobby'),
    path('story1/', story1_views.index, name="story1"),
]

story_4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

def hobby(request):
    return render(request, 'hobby.html')

story1/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

main/templates/hobby.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Hobbies</title>
{% endblock meta %}

{% block content %}
<section class="bg-green-light p-4">
	<header
		class="font-header text-center text-4xl text-white opacity-50 md:col-span-3 self-center mb-4"
	>
		Hobbies
	</header>
	<div
		class="grid grid-rows-5 md:grid-cols-3 md:grid-rows-2"
	>
		<article
			class="card-hobby overflow-hidden"
		>
			<img
				class="h-40 w-full object-cover"
				src="{% static 'images/Anime.jpg'%}"
				alt="Anime cover"
			/>
			<div class="p-4">
				<h3 class="text-xl font-secondary">Watching Anime</h3>
				<br />
				<p>
					You can check my list of anime
					<a
						href="https://anilist.co/user/TheCryptZen/"
						target="_blank"
						rel="noopener noreferrer"
						class="font-bold"
						>here</a
					>
				</p>
			</div>
		</article>

		<article class="card-hobby overflow-hidden">
			<img
				class="h-40 w-full object-cover"
				src="{% static 'images/Manga.jpg' %}"
				alt="Manga cover"
			/>
			<div class="p-4">
				<h3 class="text-xl font-secondary">Reading Manga</h3>
				<br />
				<p class="font-tertiary">
					You can check my list of manga
					<a
						href="https://anilist.co/user/TheCryptZen/"
						target="_blank"
						rel="noopener noreferrer"
						class="font-bold"
						>here</a
					>
				</p>
			</div>
		</article>

		<article
			class="card-hobby overflow-hidden"
		>
			<img
				class="h-40 w-full object-cover"
				src="{% static '/images/YouTube.jpg' %}"
				alt="Youtube cover"
			/>
			<div class="p-4">
				<h3 class="text-xl font-secondary">Watching Youtube</h3>
				<br />
				<p class="font-tertiary">
					There are a lot of useful material on YouTube
				</p>
			</div>
		</article>

		<article
			class="card-hobby overflow-hidden"
		>
			<img
				class="h-40 w-full object-cover"
				src="{% static 'images/Listening.jpg'%}"
				alt="Peoople listening to music cover"
			/>
			<div class="p-4">
				<h3 class="text-xl font-secondary">
					Listening to music
				</h3>
				<br />
				<p class="font-tertiary">
					I like to listen to music while studying or when I'm
					bored.
				</p>
			</div>
		</article>

		<article
			class="card-hobby  overflow-hidden"
		>
			<img
				src="{% static 'images/Sleeping.jpg'%}"
				alt="People sleeping cover"
				class="h-40 w-full object-cover"
			/>
			<div class="p-4">
				<h3 class="text-xl font-secondary">Sleeping</h3>
				<br />
				<p class="font-tertiary">
					That is a picture of somene sleeping. Sleeping has a
					lot of benefit and that's why it's one of my
					hobbies!
				</p>
			</div>
		</article>
	</div>
</section>
{% endblock content %}

main/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello there!</title>
{% endblock meta %}

{% block content %}	
<section
	id="home"
	class="bg-fixed p-4 bg-center bg-no-repeat relative bg-cover min-h-screen grid place-items-center md:flex md: items-center"
>
	<div class="m-4 space-y-4 md:pl-24 lg:pl-40">
		<header	
			class="text-6xl font-primary flex flex-col"
		>
			<p class="text-green font-extrabold">Teofanus</p>
			<p class="text-green opacity-50">Gary</p>
		</header>
		<div class="space-y-2">
			<p
				class="text-xl font-secondary text-orange-light place-items-center"
			>
				An aspiring computer scientist
			</p>
			<ul
				class="flex flex-row space-x-2 text-white"
			>
				<li>
					<a
						href="https://www.linkedin.com/in/garyteofanus/"
						target="_blank"
						rel="noopener noreferer"
						><svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="feather feather-linkedin w-8 h-8"
							viewBox="0 0 24 24"
						>
							<path
								d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
							/>
							<circle cx="4" cy="4" r="2" />
						</svg>
					</a>
				</li>
				<li>
					<a
						href="https://github.com/garyteofanus"
						target="_blank"
						rel="noopener noreferer"
						><svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="feather feather-github w-8 h-8"
							viewBox="0 0 24 24"
						>
							<path
								d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
							/>
						</svg>
					</a>
				</li>
				<li>
					<a
						href="https://www.instagram.com/garyteofanus/"
						target="_blank"
						rel="noopener noreferer"
						><svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="feather feather-instagram w-8 h-8"
							viewBox="0 0 24 24"
						>
							<rect
								x="2"
								y="2"
								width="20"
								height="20"
								rx="5"
								ry="5"
							/>
							<path d="M16 11a4 4 0 11-3-3 4 4 0 013 3zM18 7h0" />
						</svg>
					</a>
				</li>
				<li>
					<a
						href="mailto:garyteofanus@gmail.com"
						target="_blank"
						rel="noopener noreferer"
						><svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							class="feather feather-mail w-8 h-8"
							viewBox="0 0 24 24"
						>
							<path d="M4 4h16l2 2v12l-2 2H4l-2-2V6l2-2z" />
							<path d="M22 6l-10 7L2 6" />
						</svg>
					</a>
				</li>
			</ul>
		</div>
	</div>
</section>

{% include "home/about.html" %}

{% include "home/projects.html" %}

{% include "home/skills.html" %}

{% endblock content %}	

main/templates/home/about.html
{% load static %}
<section
	id="about-me"
	class="flex flex-col md:flex-row bg-green-dark p-4"
>
	<header class="header-right">
		ABOUT ME
	</header>
	<div class="flex justify-center content-center md:w-48 h-48 flex-none m-4">
		<img
			src="{% static 'images/Profile.png' %}"
			alt="Profile Picture"
			class="rounded-full object-contain"
		/>
	</div>
	<div class="m-4 text-white font-tertiary">
		<p>Hello! 👋</p>
		<br />
		<p>
			My name is Teofanus Gary Setiawan. I’m a sophomore computer
			science student at University of Indonesia. I’m also an avid
			coffe lover to help me in my sleepless nights.
		</p>
		<br />
		<p>
			I have some
			<a
				class="bg-green-light hover:bg-blue-700 text-white font-bold py-1 px-2 rounded"
				href="{% url 'main:hobby' %}"
				rel="noopener noreferrer"
				>hobby</a
			>
			that I like to do when I’m not busy programming.
		</p>
		<br />
		<p>My field of interest are programming and math.</p>
	</div>
</section>

main/templates/home/projects.html
{% load static %}
<section
	id="projects"
	class="flex flex-col md:flex-row bg-green-light p-4"
>
	<header class="header-left">
		PROJECTS
	</header>

	<div class="flex flex-col md:flex-row flex-wrap">
		<article class="card-hobby p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">PokeProject</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				Simple website of fun quizzes about pokemon and other stuff
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="http://poke-project.herokuapp.com/"
					target="_blank"
					class="flex flex-row space-x-2"
					rel="noopener noreferrer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://github.com/garyteofanus/pokeproject"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card-hobby p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">Story 1</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				First assignment on Web Programming and Design Course
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="{% url 'main:story1' %}"
					target="_blank"
					class="flex flex-row space-x-2"
					rel="noopener noreferrer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://gitlab.com/story-ppw/story-1"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card-hobby p-4 md:w-56">
			<h3 class="col-span-2 text-2xl font-secondary">TP4 DDP1</h3>
			<p class="text-center col-span-2 font-tertiary pt-8 pb-8">
				Web version of TP3 from Basics of Programming course
			</p>
			<div class="flex flex-row place-content-center space-x-4 pt-4">
				<a
					href="https://tp4-ddp1.herokuapp.com/"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2 cursor-not-allowed"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-globe w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<circle cx="12" cy="12" r="10" />
						<path
							d="M2 12h20M12 2a15 15 0 014 10 15 15 0 01-4 10 15 15 0 01-4-10 15 15 0 014-10z"
						/>
					</svg>
					<h5 class="self-center font-secondary">Live Site</h5>
				</a>
				<a
					href="https://github.com/garyteofanus/programming-assignment-4"
					target="_blank"
					rel="noopener noreferrer"
					class="flex flex-row space-x-2"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-6 h-6 self-center"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
					<h5 class="self-center font-secondary">Repo</h5>
				</a>
			</div>
		</article>

		<article class="card-hobby text-2xl p-4 place-items-center md:w-56">
			<h3 class="font-secondary">More Coming Soon ...</h3>
		</article>
	</div>
</section>

main/templates/home/skills.html
{% load static %}
<section
	id="skills"
	class="bg-green-dark flex flex-col md:flex-row md:justify-end p-4"
>
	<header class="header-right">
		SKILLS
	</header>
	<article class="card-hobby p-4">
		<h3 class="text-2xl font-secondary">Languanges</h3>
		<div class="grid grid-cols-2 gap-2 place-items-center pt-8">
			<object
				data="{% static 'images/Java.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				Java
			</object>
			<object
				data="{% static 'images/Python.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				Python
			</object>
			<object
				data="{% static 'images/HTML5.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				HTML5
			</object>
			<object
				data="{% static 'images/CSS3.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				CSS3
			</object>
		</div>
	</article>

	<article class="card-hobby p-4">
		<h3 class="text-2xl font-secondary">Tools</h3>
		<div class="grid grid-cols-2 gap-2 place-items-center pt-8">
			<object
				data="{% static 'images/VSCode.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				VSCode
			</object>
			<object
				data="{% static 'images/Terminal.svg' %}"
				type="image/svg+xml"
				class="h-16 w-16"
			>
				Terminal
			
			</object>
		</div>
	</article>
</section>

story1/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/story1_index.css' %}"
    />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'images/story1_favicon.png' %}"
    />
    <!--Load fonts-->
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Overpass&display=swap"
      rel="stylesheet"
    />
    <title>Story 1 - Portfolio</title>
  </head>

  <body>
    <div id="particles-js" class="container">
      <script src="{% static 'js/index.js' %}"></script>
      <div class="boxes">
        <div class="left-side">
          <div class="box-detail">
            <img
              src="{% static 'images/profile-picture.jpg' %}"
              alt="Profile picture"
              height="100vh"
              width="100vw"
            />
            <div class="section1">
              <h1><b>Teofanus Gary Setiawan</b></h1>
              <h5>Computer Science - University of Indonesia</h5>
            </div>

            <div class="section2">
              <div class="left">
                <h2>NPM:</h2>
                <h2>Batch:</h2>
                <h2>Hobi:</h2>
              </div>
              <div class="right">
                <h2>1906400160</h2>
                <h2>Maung - 2019</h2>
                <h2>Makan, nonton</h2>
              </div>
            </div>
          </div>
          <div class="box-social-media">
            <a
              class="item"
              href="https://www.instagram.com/garyteofanus/"
              target="_blank"
              ><img src="{% static 'images/instagram-icon.png' %}"
              alt="Instagram"</a
            >
            <a
              class="item"
              href="https://twitter.com/garyteofanus"
              target="_blank"
              ><img src="{% static 'images/twitter-icon.png' %}"
              alt="Twitter"</a
            >
            <a
              class="item"
              href="https://github.com/garyteofanus"
              target="_blank"
              ><img src="{% static 'images/github-icon.svg' %}" alt="GitHub"</a
            >
            <a
              class="item"
              href="https://www.linkedin.com/in/garyteofanus/"
              target="_blank"
              ><img src="{% static 'images/linkedin-icon.png' %}"
              alt="LinkedIn"</a
            >
            <a class="item" href="mailto: garyteofanus@gmail.com"
              ><img src="{% static 'images/gmail-icon.png' %}" alt="Email"
            /></a>
          </div>
        </div>

        <div class="right-side">
          <div class="box-about-me">
            <p>
              An aspiring computer scientist. Interested in security and
              programming. Currently on my third semester and having a hard
              time😭
            </p>
          </div>
          <div class="box-education-timeline">
            <div class="education-timeline-container">
              <div class="timeline-item" date-is="2019 - Now">
                <h3>Faculty of Computer Science, University of Indonesia</h3>
              </div>
              <div class="timeline-item" date-is="2016 - 2019">
                <h3>SMAK 1 BPK Penabur Bandung Highschool</h3>
              </div>
              <div class="timeline-item" date-is="2013 - 2016">
                <h3>SMP Talenta Bandung</h3>
              </div>
              <div class="timeline-item" date-is="2007 - 2013">
                <h3>SD Talenta Bandung</h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<!-- Basic Page Needs
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<meta charset="utf-8" />

	{% block meta %}
	<!-- Title for each page goes here -->
	{% endblock meta %}

	<meta name="Story 3" content="" />
	<meta name="Teofanus Gary Setiawan" content="" />

	<!-- Mobile Specific Metas
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- FONT
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link
		href="//fonts.googleapis.com/css?family=Raleway&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;800&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Signika+Negative&display=swap"
		rel="stylesheet"
		type="text/css"
	/>
	<link
		href="https://fonts.googleapis.com/css2?family=Sarala&display=swap"
		rel="stylesheet"
		type="text/css"
	/>

	<!-- CSS
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link rel="stylesheet" href="{% static 'css/index.css' %}" />

	<!-- Favicon
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
	<link
		rel="icon"
		type="image/png"
		href="{% static 'images/Logo.png' %}"
	/>
</head>

<body class="antialiased">
  	<!-- Navbar goes here -->
	<nav
		class="flex flex-row text-orange-dark font-secondary justify-around p-4 bg-green-darker"
	>
		<a href="{% url 'main:home' %}" class="hover:font-bold">Home</a>
		<a href="/#about-me" class="hover:font-bold">About Me</a>
		<a href="/#projects" class="hover:font-bold">Projects</a>
		<a href="/#skills" class="hover:font-bold">Skills</a>
		<a href="/#contacts" class="hover:font-bold">Contact</a>
	</nav>

	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

  	<!-- Footer goes here -->
  	<footer
		id="contacts"
		class="grid grid-rows-2 place-items-center space-y-2 p-4 text-white bg-green-darker"
	>
		<ul class="flex flex-row space-x-2">
			<li>
				<a
					href="https://www.linkedin.com/in/garyteofanus/"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-linkedin w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path
							d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
						/>
						<circle cx="4" cy="4" r="2" />
					</svg>
				</a>
			</li>
			<li>
				<a
					href="https://github.com/garyteofanus"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-github w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path
							d="M9 19c-5 2-5-2-7-3m14 6v-4a3 3 0 00-1-2c3-1 7-2 7-7a5 5 0 00-2-4 5 5 0 000-4l-4 1a13 13 0 00-7 0L5 1a5 5 0 000 4 5 5 0 00-1 4c0 5 3 6 6 7a3 3 0 00-1 2v4"
						/>
					</svg>
				</a>
			</li>
			<li>
				<a
					href="https://www.instagram.com/garyteofanus/"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-instagram w-8 h-8"
						viewBox="0 0 24 24"
					>
						<rect
							x="2"
							y="2"
							width="20"
							height="20"
							rx="5"
							ry="5"
						/>
						<path d="M16 11a4 4 0 11-3-3 4 4 0 013 3zM18 7h0" />
					</svg>
				</a>
			</li>
			<li>
				<a
					href="mailto:garyteofanus@gmail.com"
					target="_blank"
					rel="noopener noreferer"
					><svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-mail w-8 h-8"
						viewBox="0 0 24 24"
					>
						<path d="M4 4h16l2 2v12l-2 2H4l-2-2V6l2-2z" />
						<path d="M22 6l-10 7L2 6" />
					</svg>
				</a>
			</li>
		</ul>
		<p class="font-secondary">
			Made with 💖 by Teofanus Gary Setiawan
		</p>
	</footer>
</body>
</html>